#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_OC_EASTFORD_MAPLE	2
#define TRAINER_OC_ROUTE1_IAN		3
#define TRAINER_OC_ROUTE1_ANTHONY	4
#define TRAINER_OC_ROUTE1_HEDGE		5
#define TRAINER_OC_PIRATEBRIDGE_SAILOR1	6
#define TRAINER_OC_PIRATEBRIDGE_SAILOR2	7
#define TRAINER_OC_PIRATEBRIDGE_SAILOR3 8
#define TRAINER_OC_PIRATEBRIDGE_PIRATE 9
#define TRAINER_OC_R2_ELIWOOD 10
#define TRAINER_OC_R2_HECTOR 11
#define TRAINER_OC_R2_LYNDIS 12
#define TRAINER_OC_R2_ERROR 13
#define TRAINER_OC_R2_BAGU 14
#define TRAINER_OC_R2_JOE 15
#define TRAINER_OC_R2_GEORGE 16
#define TRAINER_OC_R2_LAURA 17
#define TRAINER_OC_R2_KNIGHT 18
#define TRAINER_OC_R2_BART 19
#define TRAINER_OC_SANCTUM_NAT 20
#define TRAINER_OC_JERRY311 21
#define TRAINER_OC_DP_ROCK 22
#define TRAINER_OC_DP_FISHER 23
#define TRAINER_OC_DP_MYSTIC1 24
#define TRAINER_OC_DP_MYSTIC2 25
#define TRAINER_OC_DP_MYSTIC3 26
#define TRAINER_OC_DP_KNIGHT1 27
#define TRAINER_OC_DP_KNIGHT2 28
#define TRAINER_OC_FT_WALLACE 29
#define TRAINER_OC_R3_SEB 30
#define TRAINER_OC_R3_ARIEL 31
#define TRAINER_OC_R3_ELLIOTT 32
#define TRAINER_OC_R3_VENDOR 33
#define TRAINER_OC_R3_KING 34
#define TRAINER_OC_R3_SAILOR1 35
#define TRAINER_OC_R3_SAILOR2 36
#define TRAINER_OC_R3_SAILOR3 37
#define TRAINER_OC_BADGE1HINT 38
#define TRAINER_OC_BADGE1 39
#define TRAINER_OC_R4_MAPLE 40
#define TRAINER_OC_R4_NEIL 41
#define TRAINER_OC_R4_BUZZ 42
#define TRAINER_OC_R4_MIKE 43
#define TRAINER_OC_R4_WOODY 44
#define TRAINER_OC_R4_JESSIE 45
#define TRAINER_OC_SPIDERCAVE_KNIGHT1 46
#define TRAINER_OC_SPIDERCAVE_KNIGHT2 47
#define TRAINER_OC_SPIDERCAVE_KNIGHT3 48
#define TRAINER_OC_SPIDERCAVE_KNIGHT4 49
#define TRAINER_OC_SPIDERCAVE_KNIGHT5 50
#define TRAINER_OC_SPIDERCAVE_KNIGHT6 51
#define TRAINER_OC_SPIDERCAVE_KNIGHT7 52
#define TRAINER_OC_SPIDERCAVE_KNIGHT8 53
#define TRAINER_OC_SPIDERCAVE_KNIGHT9 54
#define TRAINER_OC_SPIDERCAVE_ADMIN 55
#define TRAINER_OC_R5_TRAINER1 56
#define TRAINER_OC_R5_TRAINER2 57
#define TRAINER_OC_R5_TRAINER3 58
#define TRAINER_OC_R6_TETRIS 59
#define TRAINER_OC_R6_REDIGIT 60
#define TRAINER_OC_R6_STEVE 61
#define TRAINER_OC_R6_ALEX 62
#define TRAINER_OC_BADGE2HINT 63
#define TRAINER_OC_GYM2_TRAINER1 64
#define TRAINER_OC_GYM2_TRAINER2 65
#define TRAINER_OC_GYM2_TRAINER3 66
#define TRAINER_OC_BADGE2 67
#define TRAINER_OC_R7_KAPPA 68
#define TRAINER_OC_R7_LESK 69
#define TRAINER_OC_R7_SPIDEY 70
#define TRAINER_OC_R7_GOBLIN 71
#define TRAINER_OC_R7_OCTOPUS 72
#define TRAINER_OC_R7_ELECTRO 73
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          TRAINER_SAWYER_1
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       TRAINER_SAWYER_1
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       TRAINER_SAWYER_1
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       TRAINER_SAWYER_1
#define TRAINER_GABRIELLE_1                   TRAINER_SAWYER_1
#define TRAINER_GRUNT_PETALBURG_WOODS        TRAINER_SAWYER_1
#define TRAINER_MARCEL                       TRAINER_SAWYER_1
#define TRAINER_ALBERTO                      TRAINER_SAWYER_1
#define TRAINER_ED                           TRAINER_SAWYER_1
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      TRAINER_SAWYER_1
#define TRAINER_DECLAN                       TRAINER_SAWYER_1
#define TRAINER_GRUNT_RUSTURF_TUNNEL         TRAINER_SAWYER_1
#define TRAINER_GRUNT_WEATHER_INST_1         TRAINER_SAWYER_1
#define TRAINER_GRUNT_WEATHER_INST_2         TRAINER_SAWYER_1
#define TRAINER_GRUNT_WEATHER_INST_3         TRAINER_SAWYER_1
#define TRAINER_GRUNT_MUSEUM_1               TRAINER_SAWYER_1
#define TRAINER_GRUNT_MUSEUM_2               TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_1         TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_PYRE_1              TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_PYRE_2              TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_PYRE_3              TRAINER_SAWYER_1
#define TRAINER_GRUNT_WEATHER_INST_4         TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         TRAINER_SAWYER_1
#define TRAINER_FREDRICK                     TRAINER_SAWYER_1
#define TRAINER_MATT                         TRAINER_SAWYER_1
#define TRAINER_ZANDER                       TRAINER_SAWYER_1
#define TRAINER_SHELLY_WEATHER_INSTITUTE     TRAINER_SAWYER_1
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       TRAINER_SAWYER_1
#define TRAINER_ARCHIE                       TRAINER_SAWYER_1
#define TRAINER_LEAH                         TRAINER_SAWYER_1
#define TRAINER_DAISY                        TRAINER_SAWYER_1
#define TRAINER_ROSE_1                       TRAINER_SAWYER_1
#define TRAINER_FELIX                        TRAINER_SAWYER_1
#define TRAINER_VIOLET                       TRAINER_SAWYER_1
#define TRAINER_ROSE_2                       TRAINER_SAWYER_1
#define TRAINER_ROSE_3                       TRAINER_SAWYER_1
#define TRAINER_ROSE_4                       TRAINER_SAWYER_1
#define TRAINER_ROSE_5                       TRAINER_SAWYER_1
#define TRAINER_DUSTY_1                      TRAINER_SAWYER_1
#define TRAINER_CHIP                         TRAINER_SAWYER_1
#define TRAINER_FOSTER                       TRAINER_SAWYER_1
#define TRAINER_DUSTY_2                      TRAINER_SAWYER_1
#define TRAINER_DUSTY_3                      TRAINER_SAWYER_1
#define TRAINER_DUSTY_4                      TRAINER_SAWYER_1
#define TRAINER_DUSTY_5                      TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_1               TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_2               TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_3               TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_4               TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_5               TRAINER_SAWYER_1
#define TRAINER_GABBY_AND_TY_6               TRAINER_SAWYER_1
#define TRAINER_LOLA_1                       TRAINER_SAWYER_1
#define TRAINER_AUSTINA                      TRAINER_SAWYER_1
#define TRAINER_GWEN                         TRAINER_SAWYER_1
#define TRAINER_LOLA_2                       TRAINER_SAWYER_1
#define TRAINER_LOLA_3                       TRAINER_SAWYER_1
#define TRAINER_LOLA_4                       TRAINER_SAWYER_1
#define TRAINER_LOLA_5                       TRAINER_SAWYER_1
#define TRAINER_RICKY_1                      TRAINER_SAWYER_1
#define TRAINER_SIMON                        TRAINER_SAWYER_1
#define TRAINER_CHARLIE                      TRAINER_SAWYER_1
#define TRAINER_RICKY_2                      TRAINER_SAWYER_1
#define TRAINER_RICKY_3                      TRAINER_SAWYER_1
#define TRAINER_RICKY_4                      TRAINER_SAWYER_1
#define TRAINER_RICKY_5                      TRAINER_SAWYER_1
#define TRAINER_RANDALL                      TRAINER_SAWYER_1
#define TRAINER_PARKER                       TRAINER_SAWYER_1
#define TRAINER_GEORGE                       TRAINER_SAWYER_1
#define TRAINER_BERKE                        TRAINER_SAWYER_1
#define TRAINER_BRAXTON                      TRAINER_SAWYER_1
#define TRAINER_VINCENT                      TRAINER_SAWYER_1
#define TRAINER_LEROY                        TRAINER_SAWYER_1
#define TRAINER_WILTON_1                     TRAINER_SAWYER_1
#define TRAINER_EDGAR                        TRAINER_SAWYER_1
#define TRAINER_ALBERT                       TRAINER_SAWYER_1
#define TRAINER_SAMUEL                       TRAINER_SAWYER_1
#define TRAINER_VITO                         TRAINER_SAWYER_1
#define TRAINER_OWEN                         TRAINER_SAWYER_1
#define TRAINER_WILTON_2                     TRAINER_SAWYER_1
#define TRAINER_WILTON_3                     TRAINER_SAWYER_1
#define TRAINER_WILTON_4                     TRAINER_SAWYER_1
#define TRAINER_WILTON_5                     TRAINER_SAWYER_1
#define TRAINER_WARREN                       TRAINER_SAWYER_1
#define TRAINER_MARY                         TRAINER_SAWYER_1
#define TRAINER_ALEXIA                       TRAINER_SAWYER_1
#define TRAINER_JODY                         TRAINER_SAWYER_1
#define TRAINER_WENDY                        TRAINER_SAWYER_1
#define TRAINER_KEIRA                        TRAINER_SAWYER_1
#define TRAINER_BROOKE_1                     TRAINER_SAWYER_1
#define TRAINER_JENNIFER                     TRAINER_SAWYER_1
#define TRAINER_HOPE                         TRAINER_SAWYER_1
#define TRAINER_SHANNON                      TRAINER_SAWYER_1
#define TRAINER_MICHELLE                     TRAINER_SAWYER_1
#define TRAINER_CAROLINE                     TRAINER_SAWYER_1
#define TRAINER_JULIE                       TRAINER_SAWYER_1
#define TRAINER_BROOKE_2                    TRAINER_SAWYER_1
#define TRAINER_BROOKE_3                    TRAINER_SAWYER_1
#define TRAINER_BROOKE_4                    TRAINER_SAWYER_1
#define TRAINER_BROOKE_5                    TRAINER_SAWYER_1
#define TRAINER_PATRICIA                    TRAINER_SAWYER_1
#define TRAINER_KINDRA                      TRAINER_SAWYER_1
#define TRAINER_TAMMY                       TRAINER_SAWYER_1
#define TRAINER_VALERIE_1                   TRAINER_SAWYER_1
#define TRAINER_TASHA                       TRAINER_SAWYER_1
#define TRAINER_VALERIE_2                   TRAINER_SAWYER_1
#define TRAINER_VALERIE_3                   TRAINER_SAWYER_1
#define TRAINER_VALERIE_4                   TRAINER_SAWYER_1
#define TRAINER_VALERIE_5                   TRAINER_SAWYER_1
#define TRAINER_CINDY_1                     TRAINER_SAWYER_1
#define TRAINER_DAPHNE                      TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_2        TRAINER_SAWYER_1
#define TRAINER_CINDY_2                     TRAINER_SAWYER_1
#define TRAINER_BRIANNA                     TRAINER_SAWYER_1
#define TRAINER_NAOMI                       TRAINER_SAWYER_1
#define TRAINER_CINDY_3                     TRAINER_SAWYER_1
#define TRAINER_CINDY_4                     TRAINER_SAWYER_1
#define TRAINER_CINDY_5                     TRAINER_SAWYER_1
#define TRAINER_CINDY_6                     TRAINER_SAWYER_1
#define TRAINER_MELISSA                     TRAINER_SAWYER_1
#define TRAINER_SHEILA                      TRAINER_SAWYER_1
#define TRAINER_SHIRLEY                     TRAINER_SAWYER_1
#define TRAINER_JESSICA_1                   TRAINER_SAWYER_1
#define TRAINER_CONNIE                      TRAINER_SAWYER_1
#define TRAINER_BRIDGET                     TRAINER_SAWYER_1
#define TRAINER_OLIVIA                      TRAINER_SAWYER_1
#define TRAINER_TIFFANY                     TRAINER_SAWYER_1
#define TRAINER_JESSICA_2                   TRAINER_SAWYER_1
#define TRAINER_JESSICA_3                   TRAINER_SAWYER_1
#define TRAINER_JESSICA_4                   TRAINER_SAWYER_1
#define TRAINER_JESSICA_5                   TRAINER_SAWYER_1
#define TRAINER_WINSTON_1                   TRAINER_SAWYER_1
#define TRAINER_MOLLIE                      TRAINER_SAWYER_1
#define TRAINER_GARRET                      TRAINER_SAWYER_1
#define TRAINER_WINSTON_2                   TRAINER_SAWYER_1
#define TRAINER_WINSTON_3                   TRAINER_SAWYER_1
#define TRAINER_WINSTON_4                   TRAINER_SAWYER_1
#define TRAINER_WINSTON_5                   TRAINER_SAWYER_1
#define TRAINER_STEVE_1                     TRAINER_SAWYER_1
#define TRAINER_THALIA_1                    TRAINER_SAWYER_1
#define TRAINER_MARK                        TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_CHIMNEY_1          TRAINER_SAWYER_1
#define TRAINER_STEVE_2                     TRAINER_SAWYER_1
#define TRAINER_STEVE_3                     TRAINER_SAWYER_1
#define TRAINER_STEVE_4                     TRAINER_SAWYER_1
#define TRAINER_STEVE_5                     TRAINER_SAWYER_1
#define TRAINER_LUIS                        TRAINER_SAWYER_1
#define TRAINER_DOMINIK                     TRAINER_SAWYER_1
#define TRAINER_DOUGLAS                     TRAINER_SAWYER_1
#define TRAINER_DARRIN                      TRAINER_SAWYER_1
#define TRAINER_TONY_1                      TRAINER_SAWYER_1
#define TRAINER_JEROME                      TRAINER_SAWYER_1
#define TRAINER_MATTHEW                     TRAINER_SAWYER_1
#define TRAINER_DAVID                       TRAINER_SAWYER_1
#define TRAINER_SPENCER                     TRAINER_SAWYER_1
#define TRAINER_ROLAND                      TRAINER_SAWYER_1
#define TRAINER_NOLEN                       TRAINER_SAWYER_1
#define TRAINER_STAN                        TRAINER_SAWYER_1
#define TRAINER_BARRY                       TRAINER_SAWYER_1
#define TRAINER_DEAN                        TRAINER_SAWYER_1
#define TRAINER_RODNEY                      TRAINER_SAWYER_1
#define TRAINER_RICHARD                     TRAINER_SAWYER_1
#define TRAINER_HERMAN                      TRAINER_SAWYER_1
#define TRAINER_SANTIAGO                    TRAINER_SAWYER_1
#define TRAINER_GILBERT                     TRAINER_SAWYER_1
#define TRAINER_FRANKLIN                    TRAINER_SAWYER_1
#define TRAINER_KEVIN                       TRAINER_SAWYER_1
#define TRAINER_JACK                        TRAINER_SAWYER_1
#define TRAINER_DUDLEY                      TRAINER_SAWYER_1
#define TRAINER_CHAD                        TRAINER_SAWYER_1
#define TRAINER_TONY_2                      TRAINER_SAWYER_1
#define TRAINER_TONY_3                      TRAINER_SAWYER_1
#define TRAINER_TONY_4                      TRAINER_SAWYER_1
#define TRAINER_TONY_5                      TRAINER_SAWYER_1
#define TRAINER_TAKAO                       TRAINER_SAWYER_1
#define TRAINER_HITOSHI                     TRAINER_SAWYER_1
#define TRAINER_KIYO                        TRAINER_SAWYER_1
#define TRAINER_KOICHI                      TRAINER_SAWYER_1
#define TRAINER_NOB_1                       TRAINER_SAWYER_1
#define TRAINER_NOB_2                       TRAINER_SAWYER_1
#define TRAINER_NOB_3                       TRAINER_SAWYER_1
#define TRAINER_NOB_4                       TRAINER_SAWYER_1
#define TRAINER_NOB_5                       TRAINER_SAWYER_1
#define TRAINER_YUJI                        TRAINER_SAWYER_1
#define TRAINER_DAISUKE                     TRAINER_SAWYER_1
#define TRAINER_ATSUSHI                     TRAINER_SAWYER_1
#define TRAINER_KIRK                        TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        TRAINER_SAWYER_1
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        TRAINER_SAWYER_1
#define TRAINER_SHAWN                       TRAINER_SAWYER_1
#define TRAINER_FERNANDO_1                  TRAINER_SAWYER_1
#define TRAINER_DALTON_1                    TRAINER_SAWYER_1
#define TRAINER_DALTON_2                    TRAINER_SAWYER_1
#define TRAINER_DALTON_3                    TRAINER_SAWYER_1
#define TRAINER_DALTON_4                    TRAINER_SAWYER_1
#define TRAINER_DALTON_5                    TRAINER_SAWYER_1
#define TRAINER_COLE                        TRAINER_SAWYER_1
#define TRAINER_JEFF                        TRAINER_SAWYER_1
#define TRAINER_AXLE                        TRAINER_SAWYER_1
#define TRAINER_JACE                        TRAINER_SAWYER_1
#define TRAINER_KEEGAN                      TRAINER_SAWYER_1
#define TRAINER_BERNIE_1                    TRAINER_SAWYER_1
#define TRAINER_BERNIE_2                    TRAINER_SAWYER_1
#define TRAINER_BERNIE_3                    TRAINER_SAWYER_1
#define TRAINER_BERNIE_4                    TRAINER_SAWYER_1
#define TRAINER_BERNIE_5                    TRAINER_SAWYER_1
#define TRAINER_DREW                        TRAINER_SAWYER_1
#define TRAINER_BEAU                        TRAINER_SAWYER_1
#define TRAINER_LARRY                       TRAINER_SAWYER_1
#define TRAINER_SHANE                       TRAINER_SAWYER_1
#define TRAINER_JUSTIN                      TRAINER_SAWYER_1
#define TRAINER_ETHAN_1                     TRAINER_SAWYER_1
#define TRAINER_AUTUMN                      TRAINER_SAWYER_1
#define TRAINER_TRAVIS                      TRAINER_SAWYER_1
#define TRAINER_ETHAN_2                     TRAINER_SAWYER_1
#define TRAINER_ETHAN_3                     TRAINER_SAWYER_1
#define TRAINER_ETHAN_4                     TRAINER_SAWYER_1
#define TRAINER_ETHAN_5                     TRAINER_SAWYER_1
#define TRAINER_BRENT                       TRAINER_SAWYER_1
#define TRAINER_DONALD                      TRAINER_SAWYER_1
#define TRAINER_TAYLOR                      TRAINER_SAWYER_1
#define TRAINER_JEFFREY_1                   TRAINER_SAWYER_1
#define TRAINER_DEREK                       TRAINER_SAWYER_1
#define TRAINER_JEFFREY_2                   TRAINER_SAWYER_1
#define TRAINER_JEFFREY_3                   TRAINER_SAWYER_1
#define TRAINER_JEFFREY_4                   TRAINER_SAWYER_1
#define TRAINER_JEFFREY_5                   TRAINER_SAWYER_1
#define TRAINER_EDWARD                      TRAINER_SAWYER_1
#define TRAINER_PRESTON                     TRAINER_SAWYER_1
#define TRAINER_VIRGIL                      TRAINER_SAWYER_1
#define TRAINER_BLAKE                       TRAINER_SAWYER_1
#define TRAINER_WILLIAM                     TRAINER_SAWYER_1
#define TRAINER_JOSHUA                      TRAINER_SAWYER_1
#define TRAINER_CAMERON_1                   TRAINER_SAWYER_1
#define TRAINER_CAMERON_2                   TRAINER_SAWYER_1
#define TRAINER_CAMERON_3                   TRAINER_SAWYER_1
#define TRAINER_CAMERON_4                   TRAINER_SAWYER_1
#define TRAINER_CAMERON_5                   TRAINER_SAWYER_1
#define TRAINER_JACLYN                      TRAINER_SAWYER_1
#define TRAINER_HANNAH                      TRAINER_SAWYER_1
#define TRAINER_SAMANTHA                    TRAINER_SAWYER_1
#define TRAINER_MAURA                       TRAINER_SAWYER_1
#define TRAINER_KAYLA                       TRAINER_SAWYER_1
#define TRAINER_ALEXIS                      TRAINER_SAWYER_1
#define TRAINER_JACKI_1                     TRAINER_SAWYER_1
#define TRAINER_JACKI_2                     TRAINER_SAWYER_1
#define TRAINER_JACKI_3                     TRAINER_SAWYER_1
#define TRAINER_JACKI_4                     TRAINER_SAWYER_1
#define TRAINER_JACKI_5                     TRAINER_SAWYER_1
#define TRAINER_WALTER_1                    TRAINER_SAWYER_1
#define TRAINER_MICAH                       TRAINER_SAWYER_1
#define TRAINER_THOMAS                      TRAINER_SAWYER_1
#define TRAINER_WALTER_2                    TRAINER_SAWYER_1
#define TRAINER_WALTER_3                    TRAINER_SAWYER_1
#define TRAINER_WALTER_4                    TRAINER_SAWYER_1
#define TRAINER_WALTER_5                    TRAINER_SAWYER_1
#define TRAINER_SIDNEY                      TRAINER_SAWYER_1
#define TRAINER_PHOEBE                      TRAINER_SAWYER_1
#define TRAINER_GLACIA                      TRAINER_SAWYER_1
#define TRAINER_DRAKE                       TRAINER_SAWYER_1
#define TRAINER_ROXANNE_1                   TRAINER_SAWYER_1
#define TRAINER_BRAWLY_1                    TRAINER_SAWYER_1
#define TRAINER_WATTSON_1                   TRAINER_SAWYER_1
#define TRAINER_FLANNERY_1                  TRAINER_SAWYER_1
#define TRAINER_NORMAN_1                    TRAINER_SAWYER_1
#define TRAINER_WINONA_1                    TRAINER_SAWYER_1
#define TRAINER_TATE_AND_LIZA_1             TRAINER_SAWYER_1
#define TRAINER_JUAN_1                      TRAINER_SAWYER_1
#define TRAINER_JERRY_1                     TRAINER_SAWYER_1
#define TRAINER_TED                         TRAINER_SAWYER_1
#define TRAINER_PAUL                        TRAINER_SAWYER_1
#define TRAINER_JERRY_2                     TRAINER_SAWYER_1
#define TRAINER_JERRY_3                     TRAINER_SAWYER_1
#define TRAINER_JERRY_4                     TRAINER_SAWYER_1
#define TRAINER_JERRY_5                     TRAINER_SAWYER_1
#define TRAINER_KAREN_1                     TRAINER_SAWYER_1
#define TRAINER_GEORGIA                     TRAINER_SAWYER_1
#define TRAINER_KAREN_2                     TRAINER_SAWYER_1
#define TRAINER_KAREN_3                     TRAINER_SAWYER_1
#define TRAINER_KAREN_4                     TRAINER_SAWYER_1
#define TRAINER_KAREN_5                     TRAINER_SAWYER_1
#define TRAINER_KATE_AND_JOY                TRAINER_SAWYER_1
#define TRAINER_ANNA_AND_MEG_1              TRAINER_SAWYER_1
#define TRAINER_ANNA_AND_MEG_2              TRAINER_SAWYER_1
#define TRAINER_ANNA_AND_MEG_3              TRAINER_SAWYER_1
#define TRAINER_ANNA_AND_MEG_4              TRAINER_SAWYER_1
#define TRAINER_ANNA_AND_MEG_5              TRAINER_SAWYER_1
#define TRAINER_VICTOR                      TRAINER_SAWYER_1
#define TRAINER_MIGUEL_1                    TRAINER_SAWYER_1
#define TRAINER_COLTON                      TRAINER_SAWYER_1
#define TRAINER_MIGUEL_2                    TRAINER_SAWYER_1
#define TRAINER_MIGUEL_3                    TRAINER_SAWYER_1
#define TRAINER_MIGUEL_4                    TRAINER_SAWYER_1
#define TRAINER_MIGUEL_5                    TRAINER_SAWYER_1
#define TRAINER_VICTORIA                    TRAINER_SAWYER_1
#define TRAINER_VANESSA                     TRAINER_SAWYER_1
#define TRAINER_BETHANY                     TRAINER_SAWYER_1
#define TRAINER_ISABEL_1                    TRAINER_SAWYER_1
#define TRAINER_ISABEL_2                    TRAINER_SAWYER_1
#define TRAINER_ISABEL_3                    TRAINER_SAWYER_1
#define TRAINER_ISABEL_4                    TRAINER_SAWYER_1
#define TRAINER_ISABEL_5                    TRAINER_SAWYER_1
#define TRAINER_TIMOTHY_1                   TRAINER_SAWYER_1
#define TRAINER_TIMOTHY_2                   TRAINER_SAWYER_1
#define TRAINER_TIMOTHY_3                   TRAINER_SAWYER_1
#define TRAINER_TIMOTHY_4                   TRAINER_SAWYER_1
#define TRAINER_TIMOTHY_5                   TRAINER_SAWYER_1
#define TRAINER_VICKY                       TRAINER_SAWYER_1
#define TRAINER_SHELBY_1                    TRAINER_SAWYER_1
#define TRAINER_SHELBY_2                    TRAINER_SAWYER_1
#define TRAINER_SHELBY_3                    TRAINER_SAWYER_1
#define TRAINER_SHELBY_4                    TRAINER_SAWYER_1
#define TRAINER_SHELBY_5                    TRAINER_SAWYER_1
#define TRAINER_CALVIN_1                    TRAINER_SAWYER_1
#define TRAINER_BILLY                       TRAINER_SAWYER_1
#define TRAINER_JOSH                        TRAINER_SAWYER_1
#define TRAINER_TOMMY                       TRAINER_SAWYER_1
#define TRAINER_JOEY                        TRAINER_SAWYER_1
#define TRAINER_BEN                         TRAINER_SAWYER_1
#define TRAINER_QUINCY                      TRAINER_SAWYER_1
#define TRAINER_KATELYNN                    TRAINER_SAWYER_1
#define TRAINER_JAYLEN                      TRAINER_SAWYER_1
#define TRAINER_DILLON                      TRAINER_SAWYER_1
#define TRAINER_CALVIN_2                    TRAINER_SAWYER_1
#define TRAINER_CALVIN_3                    TRAINER_SAWYER_1
#define TRAINER_CALVIN_4                    TRAINER_SAWYER_1
#define TRAINER_CALVIN_5                    TRAINER_SAWYER_1
#define TRAINER_EDDIE                       TRAINER_SAWYER_1
#define TRAINER_ALLEN                       TRAINER_SAWYER_1
#define TRAINER_TIMMY                       TRAINER_SAWYER_1
#define TRAINER_WALLACE                     TRAINER_SAWYER_1
#define TRAINER_ANDREW                      TRAINER_SAWYER_1
#define TRAINER_IVAN                        TRAINER_SAWYER_1
#define TRAINER_CLAUDE                      TRAINER_SAWYER_1
#define TRAINER_ELLIOT_1                    TRAINER_SAWYER_1
#define TRAINER_NED                         TRAINER_SAWYER_1
#define TRAINER_DALE                        TRAINER_SAWYER_1
#define TRAINER_NOLAN                       TRAINER_SAWYER_1
#define TRAINER_BARNY                       TRAINER_SAWYER_1
#define TRAINER_WADE                        TRAINER_SAWYER_1
#define TRAINER_CARTER                      TRAINER_SAWYER_1
#define TRAINER_ELLIOT_2                    TRAINER_SAWYER_1
#define TRAINER_ELLIOT_3                    TRAINER_SAWYER_1
#define TRAINER_ELLIOT_4                    TRAINER_SAWYER_1
#define TRAINER_ELLIOT_5                    TRAINER_SAWYER_1
#define TRAINER_RONALD                      TRAINER_SAWYER_1
#define TRAINER_JACOB                       TRAINER_SAWYER_1
#define TRAINER_ANTHONY                     TRAINER_SAWYER_1
#define TRAINER_BENJAMIN_1                  TRAINER_SAWYER_1
#define TRAINER_BENJAMIN_2                  TRAINER_SAWYER_1
#define TRAINER_BENJAMIN_3                  TRAINER_SAWYER_1
#define TRAINER_BENJAMIN_4                  TRAINER_SAWYER_1
#define TRAINER_BENJAMIN_5                  TRAINER_SAWYER_1
#define TRAINER_ABIGAIL_1                   TRAINER_SAWYER_1
#define TRAINER_JASMINE                     TRAINER_SAWYER_1
#define TRAINER_ABIGAIL_2                   TRAINER_SAWYER_1
#define TRAINER_ABIGAIL_3                   TRAINER_SAWYER_1
#define TRAINER_ABIGAIL_4                   TRAINER_SAWYER_1
#define TRAINER_ABIGAIL_5                   TRAINER_SAWYER_1
#define TRAINER_DYLAN_1                     TRAINER_SAWYER_1
#define TRAINER_DYLAN_2                     TRAINER_SAWYER_1
#define TRAINER_DYLAN_3                     TRAINER_SAWYER_1
#define TRAINER_DYLAN_4                     TRAINER_SAWYER_1
#define TRAINER_DYLAN_5                     TRAINER_SAWYER_1
#define TRAINER_MARIA_1                     TRAINER_SAWYER_1
#define TRAINER_MARIA_2                     TRAINER_SAWYER_1
#define TRAINER_MARIA_3                     TRAINER_SAWYER_1
#define TRAINER_MARIA_4                     TRAINER_SAWYER_1
#define TRAINER_MARIA_5                     TRAINER_SAWYER_1
#define TRAINER_CAMDEN                      TRAINER_SAWYER_1
#define TRAINER_DEMETRIUS                   TRAINER_SAWYER_1
#define TRAINER_ISAIAH_1                    TRAINER_SAWYER_1
#define TRAINER_PABLO_1                     TRAINER_SAWYER_1
#define TRAINER_CHASE                       TRAINER_SAWYER_1
#define TRAINER_ISAIAH_2                    TRAINER_SAWYER_1
#define TRAINER_ISAIAH_3                    TRAINER_SAWYER_1
#define TRAINER_ISAIAH_4                    TRAINER_SAWYER_1
#define TRAINER_ISAIAH_5                    TRAINER_SAWYER_1
#define TRAINER_ISOBEL                      TRAINER_SAWYER_1
#define TRAINER_DONNY                       TRAINER_SAWYER_1
#define TRAINER_TALIA                       TRAINER_SAWYER_1
#define TRAINER_KATELYN_1                   TRAINER_SAWYER_1
#define TRAINER_ALLISON                     TRAINER_SAWYER_1
#define TRAINER_KATELYN_2                   TRAINER_SAWYER_1
#define TRAINER_KATELYN_3                   TRAINER_SAWYER_1
#define TRAINER_KATELYN_4                   TRAINER_SAWYER_1
#define TRAINER_KATELYN_5                   TRAINER_SAWYER_1
#define TRAINER_NICOLAS_1                   TRAINER_SAWYER_1
#define TRAINER_NICOLAS_2                   TRAINER_SAWYER_1
#define TRAINER_NICOLAS_3                   TRAINER_SAWYER_1
#define TRAINER_NICOLAS_4                   TRAINER_SAWYER_1
#define TRAINER_NICOLAS_5                   TRAINER_SAWYER_1
#define TRAINER_AARON                       TRAINER_SAWYER_1
#define TRAINER_PERRY                       TRAINER_SAWYER_1
#define TRAINER_HUGH                        TRAINER_SAWYER_1
#define TRAINER_PHIL                        TRAINER_SAWYER_1
#define TRAINER_JARED                       TRAINER_SAWYER_1
#define TRAINER_HUMBERTO                    TRAINER_SAWYER_1
#define TRAINER_PRESLEY                     TRAINER_SAWYER_1
#define TRAINER_EDWARDO                     TRAINER_SAWYER_1
#define TRAINER_COLIN                       TRAINER_SAWYER_1
#define TRAINER_ROBERT_1                    TRAINER_SAWYER_1
#define TRAINER_BENNY                       TRAINER_SAWYER_1
#define TRAINER_CHESTER                     TRAINER_SAWYER_1
#define TRAINER_ROBERT_2                    TRAINER_SAWYER_1
#define TRAINER_ROBERT_3                    TRAINER_SAWYER_1
#define TRAINER_ROBERT_4                    TRAINER_SAWYER_1
#define TRAINER_ROBERT_5                    TRAINER_SAWYER_1
#define TRAINER_ALEX                        TRAINER_SAWYER_1
#define TRAINER_BECK                        TRAINER_SAWYER_1
#define TRAINER_YASU                        TRAINER_SAWYER_1
#define TRAINER_TAKASHI                     TRAINER_SAWYER_1
#define TRAINER_DIANNE                      TRAINER_SAWYER_1
#define TRAINER_JANI                        TRAINER_SAWYER_1
#define TRAINER_LAO_1                       TRAINER_SAWYER_1
#define TRAINER_LUNG                        TRAINER_SAWYER_1
#define TRAINER_LAO_2                       TRAINER_SAWYER_1
#define TRAINER_LAO_3                       TRAINER_SAWYER_1
#define TRAINER_LAO_4                       TRAINER_SAWYER_1
#define TRAINER_LAO_5                       TRAINER_SAWYER_1
#define TRAINER_JOCELYN                     TRAINER_SAWYER_1
#define TRAINER_LAURA                       TRAINER_SAWYER_1
#define TRAINER_CYNDY_1                     TRAINER_SAWYER_1
#define TRAINER_CORA                        TRAINER_SAWYER_1
#define TRAINER_PAULA                       TRAINER_SAWYER_1
#define TRAINER_CYNDY_2                     TRAINER_SAWYER_1
#define TRAINER_CYNDY_3                     TRAINER_SAWYER_1
#define TRAINER_CYNDY_4                     TRAINER_SAWYER_1
#define TRAINER_CYNDY_5                     TRAINER_SAWYER_1
#define TRAINER_MADELINE_1                  TRAINER_SAWYER_1
#define TRAINER_CLARISSA                    TRAINER_SAWYER_1
#define TRAINER_ANGELICA                    TRAINER_SAWYER_1
#define TRAINER_MADELINE_2                  TRAINER_SAWYER_1
#define TRAINER_MADELINE_3                  TRAINER_SAWYER_1
#define TRAINER_MADELINE_4                  TRAINER_SAWYER_1
#define TRAINER_MADELINE_5                  TRAINER_SAWYER_1
#define TRAINER_BEVERLY                     TRAINER_SAWYER_1
#define TRAINER_IMANI                       TRAINER_SAWYER_1
#define TRAINER_KYLA                        TRAINER_SAWYER_1
#define TRAINER_DENISE                      TRAINER_SAWYER_1
#define TRAINER_BETH                        TRAINER_SAWYER_1
#define TRAINER_TARA                        TRAINER_SAWYER_1
#define TRAINER_MISSY                       TRAINER_SAWYER_1
#define TRAINER_ALICE                       TRAINER_SAWYER_1
#define TRAINER_JENNY_1                     TRAINER_SAWYER_1
#define TRAINER_GRACE                       TRAINER_SAWYER_1
#define TRAINER_TANYA                       TRAINER_SAWYER_1
#define TRAINER_SHARON                      TRAINER_SAWYER_1
#define TRAINER_NIKKI                       TRAINER_SAWYER_1
#define TRAINER_BRENDA                      TRAINER_SAWYER_1
#define TRAINER_KATIE                       TRAINER_SAWYER_1
#define TRAINER_SUSIE                       TRAINER_SAWYER_1
#define TRAINER_KARA                        TRAINER_SAWYER_1
#define TRAINER_DANA                        TRAINER_SAWYER_1
#define TRAINER_SIENNA                      TRAINER_SAWYER_1
#define TRAINER_DEBRA                       TRAINER_SAWYER_1
#define TRAINER_LINDA                       TRAINER_SAWYER_1
#define TRAINER_KAYLEE                      TRAINER_SAWYER_1
#define TRAINER_LAUREL                      TRAINER_SAWYER_1
#define TRAINER_CARLEE                      TRAINER_SAWYER_1
#define TRAINER_JENNY_2                     TRAINER_SAWYER_1
#define TRAINER_JENNY_3                     TRAINER_SAWYER_1
#define TRAINER_JENNY_4                     TRAINER_SAWYER_1
#define TRAINER_JENNY_5                     TRAINER_SAWYER_1
#define TRAINER_HEIDI                       TRAINER_SAWYER_1
#define TRAINER_BECKY                       TRAINER_SAWYER_1
#define TRAINER_CAROL                       TRAINER_SAWYER_1
#define TRAINER_NANCY                       TRAINER_SAWYER_1
#define TRAINER_MARTHA                      TRAINER_SAWYER_1
#define TRAINER_DIANA_1                     TRAINER_SAWYER_1
#define TRAINER_CEDRIC                      TRAINER_SAWYER_1
#define TRAINER_IRENE                       TRAINER_SAWYER_1
#define TRAINER_DIANA_2                     TRAINER_SAWYER_1
#define TRAINER_DIANA_3                     TRAINER_SAWYER_1
#define TRAINER_DIANA_4                     TRAINER_SAWYER_1
#define TRAINER_DIANA_5                     TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_1               TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_2               TRAINER_SAWYER_1
#define TRAINER_GINA_AND_MIA_1              TRAINER_SAWYER_1
#define TRAINER_MIU_AND_YUKI                TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_3               TRAINER_SAWYER_1
#define TRAINER_GINA_AND_MIA_2              TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_4               TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_5               TRAINER_SAWYER_1
#define TRAINER_AMY_AND_LIV_6               TRAINER_SAWYER_1
#define TRAINER_HUEY                        TRAINER_SAWYER_1
#define TRAINER_EDMOND                      TRAINER_SAWYER_1
#define TRAINER_ERNEST_1                    TRAINER_SAWYER_1
#define TRAINER_DWAYNE                      TRAINER_SAWYER_1
#define TRAINER_PHILLIP                     TRAINER_SAWYER_1
#define TRAINER_LEONARD                     TRAINER_SAWYER_1
#define TRAINER_DUNCAN                      TRAINER_SAWYER_1
#define TRAINER_ERNEST_2                    TRAINER_SAWYER_1
#define TRAINER_ERNEST_3                    TRAINER_SAWYER_1
#define TRAINER_ERNEST_4                    TRAINER_SAWYER_1
#define TRAINER_ERNEST_5                    TRAINER_SAWYER_1
#define TRAINER_ELI                         TRAINER_SAWYER_1
#define TRAINER_ANNIKA                      TRAINER_SAWYER_1
#define TRAINER_JAZMYN                      TRAINER_SAWYER_1
#define TRAINER_JONAS                       TRAINER_SAWYER_1
#define TRAINER_KAYLEY                      TRAINER_SAWYER_1
#define TRAINER_AURON                       TRAINER_SAWYER_1
#define TRAINER_KELVIN                      TRAINER_SAWYER_1
#define TRAINER_MARLEY                      TRAINER_SAWYER_1
#define TRAINER_REYNA                       TRAINER_SAWYER_1
#define TRAINER_HUDSON                      TRAINER_SAWYER_1
#define TRAINER_CONOR                       TRAINER_SAWYER_1
#define TRAINER_EDWIN_1                     TRAINER_SAWYER_1
#define TRAINER_HECTOR                      TRAINER_SAWYER_1
#define TRAINER_TABITHA_MOSSDEEP            TRAINER_SAWYER_1
#define TRAINER_EDWIN_2                     TRAINER_SAWYER_1
#define TRAINER_EDWIN_3                     TRAINER_SAWYER_1
#define TRAINER_EDWIN_4                     TRAINER_SAWYER_1
#define TRAINER_EDWIN_5                     TRAINER_SAWYER_1
#define TRAINER_WALLY_VR_1                  TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   TRAINER_SAWYER_1
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_103_MUDKIP        TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_110_MUDKIP        TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_119_MUDKIP        TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_103_TREECKO       TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_110_TREECKO       TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_119_TREECKO       TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_103_TORCHIC       TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_110_TORCHIC       TRAINER_SAWYER_1
#define TRAINER_MAY_ROUTE_119_TORCHIC       TRAINER_SAWYER_1
#define TRAINER_ISAAC_1                     TRAINER_SAWYER_1
#define TRAINER_DAVIS                       TRAINER_SAWYER_1
#define TRAINER_MITCHELL                    TRAINER_SAWYER_1
#define TRAINER_ISAAC_2                     TRAINER_SAWYER_1
#define TRAINER_ISAAC_3                     TRAINER_SAWYER_1
#define TRAINER_ISAAC_4                     TRAINER_SAWYER_1
#define TRAINER_ISAAC_5                     TRAINER_SAWYER_1
#define TRAINER_LYDIA_1                     TRAINER_SAWYER_1
#define TRAINER_HALLE                       TRAINER_SAWYER_1
#define TRAINER_GARRISON                    TRAINER_SAWYER_1
#define TRAINER_LYDIA_2                     TRAINER_SAWYER_1
#define TRAINER_LYDIA_3                     TRAINER_SAWYER_1
#define TRAINER_LYDIA_4                     TRAINER_SAWYER_1
#define TRAINER_LYDIA_5                     TRAINER_SAWYER_1
#define TRAINER_JACKSON_1                   TRAINER_SAWYER_1
#define TRAINER_LORENZO                     TRAINER_SAWYER_1
#define TRAINER_SEBASTIAN                   TRAINER_SAWYER_1
#define TRAINER_JACKSON_2                   TRAINER_SAWYER_1
#define TRAINER_JACKSON_3                   TRAINER_SAWYER_1
#define TRAINER_JACKSON_4                   TRAINER_SAWYER_1
#define TRAINER_JACKSON_5                   TRAINER_SAWYER_1
#define TRAINER_CATHERINE_1                 TRAINER_SAWYER_1
#define TRAINER_JENNA                       TRAINER_SAWYER_1
#define TRAINER_SOPHIA                      TRAINER_SAWYER_1
#define TRAINER_CATHERINE_2                 TRAINER_SAWYER_1
#define TRAINER_CATHERINE_3                 TRAINER_SAWYER_1
#define TRAINER_CATHERINE_4                 TRAINER_SAWYER_1
#define TRAINER_CATHERINE_5                 TRAINER_SAWYER_1
#define TRAINER_JULIO                       TRAINER_SAWYER_1
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     TRAINER_SAWYER_1
#define TRAINER_GRUNT_UNUSED                TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_PYRE_4             TRAINER_SAWYER_1
#define TRAINER_GRUNT_JAGGED_PASS           TRAINER_SAWYER_1
#define TRAINER_MARC                        TRAINER_SAWYER_1
#define TRAINER_BRENDEN                     TRAINER_SAWYER_1
#define TRAINER_LILITH                      TRAINER_SAWYER_1
#define TRAINER_CRISTIAN                    TRAINER_SAWYER_1
#define TRAINER_SYLVIA                      TRAINER_SAWYER_1
#define TRAINER_LEONARDO                    TRAINER_SAWYER_1
#define TRAINER_ATHENA                      TRAINER_SAWYER_1
#define TRAINER_HARRISON                    TRAINER_SAWYER_1
#define TRAINER_GRUNT_MT_CHIMNEY_2          TRAINER_SAWYER_1
#define TRAINER_CLARENCE                    TRAINER_SAWYER_1
#define TRAINER_TERRY                       TRAINER_SAWYER_1
#define TRAINER_NATE                        TRAINER_SAWYER_1
#define TRAINER_KATHLEEN                    TRAINER_SAWYER_1
#define TRAINER_CLIFFORD                    TRAINER_SAWYER_1
#define TRAINER_NICHOLAS                    TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_3        TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_4        TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_5        TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_6        TRAINER_SAWYER_1
#define TRAINER_GRUNT_SPACE_CENTER_7        TRAINER_SAWYER_1
#define TRAINER_MACEY                       TRAINER_SAWYER_1
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     TRAINER_SAWYER_1
#define TRAINER_PAXTON                      TRAINER_SAWYER_1
#define TRAINER_ISABELLA                    TRAINER_SAWYER_1
#define TRAINER_GRUNT_WEATHER_INST_5        TRAINER_SAWYER_1
#define TRAINER_TABITHA_MT_CHIMNEY          TRAINER_SAWYER_1
#define TRAINER_JONATHAN                    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    TRAINER_SAWYER_1
#define TRAINER_MAY_RUSTBORO_MUDKIP         TRAINER_SAWYER_1
#define TRAINER_MAXIE_MAGMA_HIDEOUT         TRAINER_SAWYER_1
#define TRAINER_MAXIE_MT_CHIMNEY            TRAINER_SAWYER_1
#define TRAINER_TIANA                       TRAINER_SAWYER_1
#define TRAINER_HALEY_1                     TRAINER_SAWYER_1
#define TRAINER_JANICE                      TRAINER_SAWYER_1
#define TRAINER_VIVI                        TRAINER_SAWYER_1
#define TRAINER_HALEY_2                     TRAINER_SAWYER_1
#define TRAINER_HALEY_3                     TRAINER_SAWYER_1
#define TRAINER_HALEY_4                     TRAINER_SAWYER_1
#define TRAINER_HALEY_5                     TRAINER_SAWYER_1
#define TRAINER_SALLY                       TRAINER_SAWYER_1
#define TRAINER_ROBIN                       TRAINER_SAWYER_1
#define TRAINER_ANDREA                      TRAINER_SAWYER_1
#define TRAINER_CRISSY                      TRAINER_SAWYER_1
#define TRAINER_RICK                        TRAINER_SAWYER_1
#define TRAINER_LYLE                        TRAINER_SAWYER_1
#define TRAINER_JOSE                        TRAINER_SAWYER_1
#define TRAINER_DOUG                        TRAINER_SAWYER_1
#define TRAINER_GREG                        TRAINER_SAWYER_1
#define TRAINER_KENT                        TRAINER_SAWYER_1
#define TRAINER_JAMES_1                     TRAINER_SAWYER_1
#define TRAINER_JAMES_2                     TRAINER_SAWYER_1
#define TRAINER_JAMES_3                     TRAINER_SAWYER_1
#define TRAINER_JAMES_4                     TRAINER_SAWYER_1
#define TRAINER_JAMES_5                     TRAINER_SAWYER_1
#define TRAINER_BRICE                       TRAINER_SAWYER_1
#define TRAINER_TRENT_1                     TRAINER_SAWYER_1
#define TRAINER_LENNY                       TRAINER_SAWYER_1
#define TRAINER_LUCAS_1                     TRAINER_SAWYER_1
#define TRAINER_ALAN                        TRAINER_SAWYER_1
#define TRAINER_CLARK                       TRAINER_SAWYER_1
#define TRAINER_ERIC                        TRAINER_SAWYER_1
#define TRAINER_LUCAS_2                     TRAINER_SAWYER_1
#define TRAINER_MIKE_1                      TRAINER_SAWYER_1
#define TRAINER_MIKE_2                      TRAINER_SAWYER_1
#define TRAINER_TRENT_2                     TRAINER_SAWYER_1
#define TRAINER_TRENT_3                     TRAINER_SAWYER_1
#define TRAINER_TRENT_4                     TRAINER_SAWYER_1
#define TRAINER_TRENT_5                     TRAINER_SAWYER_1
#define TRAINER_DEZ_AND_LUKE                TRAINER_SAWYER_1
#define TRAINER_LEA_AND_JED                 TRAINER_SAWYER_1
#define TRAINER_KIRA_AND_DAN_1              TRAINER_SAWYER_1
#define TRAINER_KIRA_AND_DAN_2              TRAINER_SAWYER_1
#define TRAINER_KIRA_AND_DAN_3              TRAINER_SAWYER_1
#define TRAINER_KIRA_AND_DAN_4              TRAINER_SAWYER_1
#define TRAINER_KIRA_AND_DAN_5              TRAINER_SAWYER_1
#define TRAINER_JOHANNA                     TRAINER_SAWYER_1
#define TRAINER_GERALD                      TRAINER_SAWYER_1
#define TRAINER_VIVIAN                      TRAINER_SAWYER_1
#define TRAINER_DANIELLE                    TRAINER_SAWYER_1
#define TRAINER_HIDEO                       TRAINER_SAWYER_1
#define TRAINER_KEIGO                       TRAINER_SAWYER_1
#define TRAINER_RILEY                       TRAINER_SAWYER_1
#define TRAINER_FLINT                       TRAINER_SAWYER_1
#define TRAINER_ASHLEY                      TRAINER_SAWYER_1
#define TRAINER_WALLY_MAUVILLE              TRAINER_SAWYER_1
#define TRAINER_WALLY_VR_2                  TRAINER_SAWYER_1
#define TRAINER_WALLY_VR_3                  TRAINER_SAWYER_1
#define TRAINER_WALLY_VR_4                  TRAINER_SAWYER_1
#define TRAINER_WALLY_VR_5                  TRAINER_SAWYER_1
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     TRAINER_SAWYER_1
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    TRAINER_SAWYER_1
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    TRAINER_SAWYER_1
#define TRAINER_MAY_LILYCOVE_MUDKIP         TRAINER_SAWYER_1
#define TRAINER_MAY_LILYCOVE_TREECKO        TRAINER_SAWYER_1
#define TRAINER_MAY_LILYCOVE_TORCHIC        TRAINER_SAWYER_1
#define TRAINER_JONAH                       TRAINER_SAWYER_1
#define TRAINER_HENRY                       TRAINER_SAWYER_1
#define TRAINER_ROGER                       TRAINER_SAWYER_1
#define TRAINER_ALEXA                       TRAINER_SAWYER_1
#define TRAINER_RUBEN                       TRAINER_SAWYER_1
#define TRAINER_KOJI_1                      TRAINER_SAWYER_1
#define TRAINER_WAYNE                       TRAINER_SAWYER_1
#define TRAINER_AIDAN                       TRAINER_SAWYER_1
#define TRAINER_REED                        TRAINER_SAWYER_1
#define TRAINER_TISHA                       TRAINER_SAWYER_1
#define TRAINER_TORI_AND_TIA                TRAINER_SAWYER_1
#define TRAINER_KIM_AND_IRIS                TRAINER_SAWYER_1
#define TRAINER_TYRA_AND_IVY                TRAINER_SAWYER_1
#define TRAINER_MEL_AND_PAUL                TRAINER_SAWYER_1
#define TRAINER_JOHN_AND_JAY_1              TRAINER_SAWYER_1
#define TRAINER_JOHN_AND_JAY_2              TRAINER_SAWYER_1
#define TRAINER_JOHN_AND_JAY_3              TRAINER_SAWYER_1
#define TRAINER_JOHN_AND_JAY_4              TRAINER_SAWYER_1
#define TRAINER_JOHN_AND_JAY_5              TRAINER_SAWYER_1
#define TRAINER_RELI_AND_IAN                TRAINER_SAWYER_1
#define TRAINER_LILA_AND_ROY_1              TRAINER_SAWYER_1
#define TRAINER_LILA_AND_ROY_2              TRAINER_SAWYER_1
#define TRAINER_LILA_AND_ROY_3              TRAINER_SAWYER_1
#define TRAINER_LILA_AND_ROY_4              TRAINER_SAWYER_1
#define TRAINER_LILA_AND_ROY_5              TRAINER_SAWYER_1
#define TRAINER_LISA_AND_RAY                TRAINER_SAWYER_1
#define TRAINER_CHRIS                       TRAINER_SAWYER_1
#define TRAINER_DAWSON                      TRAINER_SAWYER_1
#define TRAINER_SARAH                       TRAINER_SAWYER_1
#define TRAINER_DARIAN                      TRAINER_SAWYER_1
#define TRAINER_HAILEY                      TRAINER_SAWYER_1
#define TRAINER_CHANDLER                    TRAINER_SAWYER_1
#define TRAINER_KALEB                       TRAINER_SAWYER_1
#define TRAINER_JOSEPH                      TRAINER_SAWYER_1
#define TRAINER_ALYSSA                      TRAINER_SAWYER_1
#define TRAINER_MARCOS                      TRAINER_SAWYER_1
#define TRAINER_RHETT                       TRAINER_SAWYER_1
#define TRAINER_TYRON                       TRAINER_SAWYER_1
#define TRAINER_CELINA                      TRAINER_SAWYER_1
#define TRAINER_BIANCA                      TRAINER_SAWYER_1
#define TRAINER_HAYDEN                      TRAINER_SAWYER_1
#define TRAINER_SOPHIE                      TRAINER_SAWYER_1
#define TRAINER_COBY                        TRAINER_SAWYER_1
#define TRAINER_LAWRENCE                    TRAINER_SAWYER_1
#define TRAINER_WYATT                       TRAINER_SAWYER_1
#define TRAINER_ANGELINA                    TRAINER_SAWYER_1
#define TRAINER_KAI                         TRAINER_SAWYER_1
#define TRAINER_CHARLOTTE                   TRAINER_SAWYER_1
#define TRAINER_DEANDRE                     TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      TRAINER_SAWYER_1
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      TRAINER_SAWYER_1
#define TRAINER_TABITHA_MAGMA_HIDEOUT       TRAINER_SAWYER_1
#define TRAINER_DARCY                       TRAINER_SAWYER_1
#define TRAINER_MAXIE_MOSSDEEP              TRAINER_SAWYER_1
#define TRAINER_PETE                        TRAINER_SAWYER_1
#define TRAINER_ISABELLE                    TRAINER_SAWYER_1
#define TRAINER_ANDRES_1                    TRAINER_SAWYER_1
#define TRAINER_JOSUE                       TRAINER_SAWYER_1
#define TRAINER_CAMRON                      TRAINER_SAWYER_1
#define TRAINER_CORY_1                      TRAINER_SAWYER_1
#define TRAINER_CAROLINA                    TRAINER_SAWYER_1
#define TRAINER_ELIJAH                      TRAINER_SAWYER_1
#define TRAINER_CELIA                       TRAINER_SAWYER_1
#define TRAINER_BRYAN                       TRAINER_SAWYER_1
#define TRAINER_BRANDEN                     TRAINER_SAWYER_1
#define TRAINER_BRYANT                      TRAINER_SAWYER_1
#define TRAINER_SHAYLA                      TRAINER_SAWYER_1
#define TRAINER_KYRA                        TRAINER_SAWYER_1
#define TRAINER_JAIDEN                      TRAINER_SAWYER_1
#define TRAINER_ALIX                        TRAINER_SAWYER_1
#define TRAINER_HELENE                      TRAINER_SAWYER_1
#define TRAINER_MARLENE                     TRAINER_SAWYER_1
#define TRAINER_DEVAN                       TRAINER_SAWYER_1
#define TRAINER_JOHNSON                     TRAINER_SAWYER_1
#define TRAINER_MELINA                      TRAINER_SAWYER_1
#define TRAINER_BRANDI                      TRAINER_SAWYER_1
#define TRAINER_AISHA                       TRAINER_SAWYER_1
#define TRAINER_MAKAYLA                     TRAINER_SAWYER_1
#define TRAINER_FABIAN                      TRAINER_SAWYER_1
#define TRAINER_DAYTON                      TRAINER_SAWYER_1
#define TRAINER_RACHEL                      TRAINER_SAWYER_1
#define TRAINER_LEONEL                      TRAINER_SAWYER_1
#define TRAINER_CALLIE                      TRAINER_SAWYER_1
#define TRAINER_CALE                        TRAINER_SAWYER_1
#define TRAINER_MYLES                       TRAINER_SAWYER_1
#define TRAINER_PAT                         TRAINER_SAWYER_1
#define TRAINER_CRISTIN_1                   TRAINER_SAWYER_1
#define TRAINER_MAY_RUSTBORO_TREECKO        TRAINER_SAWYER_1
#define TRAINER_MAY_RUSTBORO_TORCHIC        TRAINER_SAWYER_1
#define TRAINER_ROXANNE_2                   TRAINER_SAWYER_1
#define TRAINER_ROXANNE_3                   TRAINER_SAWYER_1
#define TRAINER_ROXANNE_4                   TRAINER_SAWYER_1
#define TRAINER_ROXANNE_5                   TRAINER_SAWYER_1
#define TRAINER_BRAWLY_2                    TRAINER_SAWYER_1
#define TRAINER_BRAWLY_3                    TRAINER_SAWYER_1
#define TRAINER_BRAWLY_4                    TRAINER_SAWYER_1
#define TRAINER_BRAWLY_5                    TRAINER_SAWYER_1
#define TRAINER_WATTSON_2                   TRAINER_SAWYER_1
#define TRAINER_WATTSON_3                   TRAINER_SAWYER_1
#define TRAINER_WATTSON_4                   TRAINER_SAWYER_1
#define TRAINER_WATTSON_5                   TRAINER_SAWYER_1
#define TRAINER_FLANNERY_2                  TRAINER_SAWYER_1
#define TRAINER_FLANNERY_3                  TRAINER_SAWYER_1
#define TRAINER_FLANNERY_4                  TRAINER_SAWYER_1
#define TRAINER_FLANNERY_5                  TRAINER_SAWYER_1
#define TRAINER_NORMAN_2                    TRAINER_SAWYER_1
#define TRAINER_NORMAN_3                    TRAINER_SAWYER_1
#define TRAINER_NORMAN_4                    TRAINER_SAWYER_1
#define TRAINER_NORMAN_5                    TRAINER_SAWYER_1
#define TRAINER_WINONA_2                    TRAINER_SAWYER_1
#define TRAINER_WINONA_3                    TRAINER_SAWYER_1
#define TRAINER_WINONA_4                    TRAINER_SAWYER_1
#define TRAINER_WINONA_5                    TRAINER_SAWYER_1
#define TRAINER_TATE_AND_LIZA_2             TRAINER_SAWYER_1
#define TRAINER_TATE_AND_LIZA_3             TRAINER_SAWYER_1
#define TRAINER_TATE_AND_LIZA_4             TRAINER_SAWYER_1
#define TRAINER_TATE_AND_LIZA_5             TRAINER_SAWYER_1
#define TRAINER_JUAN_2                      TRAINER_SAWYER_1
#define TRAINER_JUAN_3                      TRAINER_SAWYER_1
#define TRAINER_JUAN_4                      TRAINER_SAWYER_1
#define TRAINER_JUAN_5                      TRAINER_SAWYER_1
#define TRAINER_ANGELO                      TRAINER_SAWYER_1
#define TRAINER_DARIUS                      TRAINER_SAWYER_1
#define TRAINER_STEVEN                      TRAINER_SAWYER_1
#define TRAINER_ANABEL                      TRAINER_SAWYER_1
#define TRAINER_TUCKER                      TRAINER_SAWYER_1
#define TRAINER_SPENSER                     TRAINER_SAWYER_1
#define TRAINER_GRETA                       TRAINER_SAWYER_1
#define TRAINER_NOLAND                      TRAINER_SAWYER_1
#define TRAINER_LUCY                        TRAINER_SAWYER_1
#define TRAINER_BRANDON                     TRAINER_SAWYER_1
#define TRAINER_ANDRES_2                    TRAINER_SAWYER_1
#define TRAINER_ANDRES_3                    TRAINER_SAWYER_1
#define TRAINER_ANDRES_4                    TRAINER_SAWYER_1
#define TRAINER_ANDRES_5                    TRAINER_SAWYER_1
#define TRAINER_CORY_2                      TRAINER_SAWYER_1
#define TRAINER_CORY_3                      TRAINER_SAWYER_1
#define TRAINER_CORY_4                      TRAINER_SAWYER_1
#define TRAINER_CORY_5                      TRAINER_SAWYER_1
#define TRAINER_PABLO_2                     TRAINER_SAWYER_1
#define TRAINER_PABLO_3                     TRAINER_SAWYER_1
#define TRAINER_PABLO_4                     TRAINER_SAWYER_1
#define TRAINER_PABLO_5                     TRAINER_SAWYER_1
#define TRAINER_KOJI_2                      TRAINER_SAWYER_1
#define TRAINER_KOJI_3                      TRAINER_SAWYER_1
#define TRAINER_KOJI_4                      TRAINER_SAWYER_1
#define TRAINER_KOJI_5                      TRAINER_SAWYER_1
#define TRAINER_CRISTIN_2                   TRAINER_SAWYER_1
#define TRAINER_CRISTIN_3                   TRAINER_SAWYER_1
#define TRAINER_CRISTIN_4                   TRAINER_SAWYER_1
#define TRAINER_CRISTIN_5                   TRAINER_SAWYER_1
#define TRAINER_FERNANDO_2                  TRAINER_SAWYER_1
#define TRAINER_FERNANDO_3                  TRAINER_SAWYER_1
#define TRAINER_FERNANDO_4                  TRAINER_SAWYER_1
#define TRAINER_FERNANDO_5                  TRAINER_SAWYER_1
#define TRAINER_SAWYER_2                    TRAINER_SAWYER_1
#define TRAINER_SAWYER_3                    TRAINER_SAWYER_1
#define TRAINER_SAWYER_4                    TRAINER_SAWYER_1
#define TRAINER_SAWYER_5                    TRAINER_SAWYER_1
#define TRAINER_GABRIELLE_2                 TRAINER_SAWYER_1
#define TRAINER_GABRIELLE_3                 TRAINER_SAWYER_1
#define TRAINER_GABRIELLE_4                 TRAINER_SAWYER_1
#define TRAINER_GABRIELLE_5                 TRAINER_SAWYER_1
#define TRAINER_THALIA_2                    TRAINER_SAWYER_1
#define TRAINER_THALIA_3                    TRAINER_SAWYER_1
#define TRAINER_THALIA_4                    TRAINER_SAWYER_1
#define TRAINER_THALIA_5                    TRAINER_SAWYER_1
#define TRAINER_MARIELA                     TRAINER_SAWYER_1
#define TRAINER_ALVARO                      TRAINER_SAWYER_1
#define TRAINER_EVERETT                     TRAINER_SAWYER_1
#define TRAINER_RED                         TRAINER_SAWYER_1
#define TRAINER_LEAF                        TRAINER_SAWYER_1
#define TRAINER_BRENDAN_PLACEHOLDER         TRAINER_SAWYER_1
#define TRAINER_MAY_PLACEHOLDER             TRAINER_SAWYER_1

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
