SafariZoneNE_MapScripts::
	.byte 0
SafariZoneNE_ES_Sign1::
	msgbox SafariZoneNE_Text_Sign1, MSGBOX_SIGN
	end
SafariZoneNE_ES_Sign2::
	msgbox SafariZoneNE_Text_Sign2, MSGBOX_SIGN
	end
SafariZoneNE_ES_Sign3::
	msgbox SafariZoneNE_Text_Sign3, MSGBOX_SIGN
	end
SafariZoneSE_ES_Sign1::
	msgbox SafariZoneSE_Text_Sign1, MSGBOX_SIGN
	end
SafariZoneSE_ES_Sign2::
	msgbox SafariZoneSE_Text_Sign2, MSGBOX_SIGN
	end
SafariZoneSE_ES_Sign3::
	msgbox SafariZoneSE_Text_Sign3, MSGBOX_SIGN
	end
SafariZoneSW_ES_Sign1::
	msgbox SafariZoneSW_Text_Sign1, MSGBOX_SIGN
	end
SafariZoneSW_ES_Sign2::
	msgbox SafariZoneSW_Text_Sign2, MSGBOX_SIGN
	end
SafariZoneSW_ES_Sign3::
	msgbox SafariZoneSW_Text_Sign3, MSGBOX_SIGN
	end
SafariZoneNW_ES_Sign1::
	msgbox SafariZoneNW_Text_Sign1, MSGBOX_SIGN
	end
SafariZoneNW_ES_Sign2::
	msgbox SafariZoneNW_Text_Sign2, MSGBOX_SIGN
	end
SafariZoneNW_ES_Sign3::
	msgbox SafariZoneNW_Text_Sign3, MSGBOX_SIGN
	end
SafariZoneNE_Text_Sign1:
	.string "Coldlands: An icy biome themed\n"
	.string "after Emperor Matthew Moonstone.$"
SafariZoneNE_Text_Sign2:
	.string "{LEFT_ARROW} Highlands$"
SafariZoneNE_Text_Sign3:
	.string "{DOWN_ARROW} Wetlands$"
SafariZoneSE_Text_Sign1:
	.string "Wetlands: A humid biome themed\n"
	.string "after Princess Rosalyn Reyes.$"
SafariZoneSE_Text_Sign2:
	.string "{UP_ARROW} Coldlands$"
SafariZoneSE_Text_Sign3:
	.string "{LEFT_ARROW} Hotlands$"
SafariZoneSW_Text_Sign1:
	.string "Hotlands: A hot biome themed\n"
	.string "after Empress Melina Moonstone.$"
SafariZoneSW_Text_Sign2:
	.string "{RIGHT_ARROW} Wetlands$"
SafariZoneSW_Text_Sign3:
	.string "{UP_ARROW} Highlands$"
SafariZoneNW_Text_Sign1:
	.string "Highlands: A hilly biome themed after\n"
	.string "Grand Duchess Emily Sunstone.$"
SafariZoneNW_Text_Sign2:
	.string "{DOWN_ARROW} Hotlands$"
SafariZoneNW_Text_Sign3:
	.string "{RIGHT_ARROW} Coldlands$"